/**
 * Structured logging that CANNOT leak conversation content.
 *
 * Barkly's users are children talking to a dog about their day. The brief is
 * explicit: production logging without storing sensitive conversation content.
 *
 * So the guarantee here is mechanical, not a matter of discipline:
 *
 * - There is no "message" argument. You log an event name plus a flat record.
 * - Numbers and booleans always pass (a token count cannot spell a name).
 * - A STRING passes only if its field name is on FIELDS, an explicit list of
 *   operational identifiers. `speech: "..."` is not on it, so it is dropped
 *   entirely rather than truncated. (Truncation was the first version of this
 *   and its own test caught it: the first 48 characters of "my name is Sam
 *   and I live at 12 Elm Street" is still a child's address.)
 * - Objects and arrays are dropped unconditionally — that is where a whole
 *   message array would arrive.
 *
 * Adding a field to FIELDS is therefore a deliberate act with a reviewer.
 *
 * Device identifiers are hashed before they are written, so a log file is not
 * a list of who talked to Barkly.
 */

import { createHash } from 'node:crypto';

const LEVELS = { debug: 10, info: 20, warn: 30, error: 40 };

/**
 * The only string fields that may be logged. Every one is generated by this
 * server or is a fixed identifier — none is derived from user speech.
 */
export const FIELDS = new Set([
  'env',
  'event',
  'reason',
  'error',
  'path',
  'method',
  'model',
  'requestId',
  'device',
  'status',
  'pricing',
  'origins',
  'appToken',
  'provider',
  'version',
]);

const MAX_FIELD = 200;

export function scrub(fields) {
  const out = {};
  for (const [k, v] of Object.entries(fields || {})) {
    if (v === null || v === undefined) continue;
    if (typeof v === 'number' || typeof v === 'boolean') {
      out[k] = v;
      continue;
    }
    if (typeof v !== 'string') continue; // objects/arrays could be message content
    if (!FIELDS.has(k)) continue; // not an approved operational field: dropped
    out[k] = v.length > MAX_FIELD ? `${v.slice(0, MAX_FIELD)}...` : v;
  }
  return out;
}

/** Stable, non-reversible device id for correlating abuse without identifying a child. */
export function hashId(raw, salt = '') {
  if (!raw) return 'anon';
  return createHash('sha256').update(`${salt}:${raw}`).digest('hex').slice(0, 12);
}

export function createLogger({ level = 'info', env = 'development', sink = console.log } = {}) {
  const min = LEVELS[level] ?? LEVELS.info;
  const emit = (lvl, event, fields) => {
    if (LEVELS[lvl] < min) return;
    sink(JSON.stringify({ ts: new Date().toISOString(), lvl, env, event, ...scrub(fields) }));
  };
  return {
    debug: (event, fields) => emit('debug', event, fields),
    info: (event, fields) => emit('info', event, fields),
    warn: (event, fields) => emit('warn', event, fields),
    error: (event, fields) => emit('error', event, fields),
  };
}
