#!/usr/bin/env python3
"""Emit the handoff timeline for v37 "THE WORLD / THE LAYER".

SECTIONS and the narration script are read out of spec_layer.py/
vo_layer.py, not retyped. The per-section SHOT STRUCTURE is a direct
account of render_layer.py's own per-section builder code, written by
reading it.
"""
import sys

sys.path.insert(0, ".")
from spec_layer import SECTIONS, VO_LINES, TOTAL, W, H, FPS

STRUCTURE = {
    "hook": [
        "0.0-8.0s   IMG_6790 @0.5s real footage, bright_edit_grade -- "
        "the film's own daylight treatment (opposite instinct from "
        "map/'s dark_doc_grade). r203: shifted from @8.0s -- ChatGPT's "
        "r202 review pushed back on r201's 2-clip \"unfixable\" claim; "
        "a full audit of all 33 real candid clips (r203__claude__v37_"
        "gaze_alignment_audit.md) found exactly one genuine gaze-"
        "aligned moment in the whole library, right here at raw "
        "t~3.5-7.0s, previously unused because hook's own in-point "
        "started 0.5s after this stretch ends.",
        "0.0-1.8s   clean world, no layer -- \"hold clean real footage "
        "for at least 1.5 seconds\" (r184's own beat-1 requirement)",
        "1.8-4.2s   windowed_reveal(direction=ltr, r197): the real "
        "footage stays full-bleed at every value of progress -- a "
        "bracket-framed floating AR window sweeps open, exposing "
        "ai/iceage/iceage_falls_visualization_r172_chatgpt.jpg inside "
        "the window only, never the whole picture; a coral seam marks "
        "the sweep's leading edge while it is mid-open (replaces r185's "
        "wipe_reveal, a full-frame crossfade to an unrelated photo -- "
        "the operator's direct complaint: \"we cut to an AI image, it's "
        "out of place... it doesn't give the feel... you walk around "
        "with glasses and you see stuff\"). r203: the window is "
        "repositioned for this shot only (win_cx=1000/1920, "
        "win_cy=470/1080, same size -- every other windowed_reveal call "
        "keeps the shared default position) to sit exactly where the "
        "wearer points at local t~3.0-6.5s -- see STANDING AR GRAMMAR.",
        "3.0-6.5s   the wearer turns toward camera and extends his arm, "
        "pointing at the real signage -- and, with the window "
        "repositioned, at the AR window itself. This is the ONE moment "
        "found across the full 33-clip audit where the wearer's own "
        "gesture aligns with the visualization instead of it floating "
        "beside him unnoticed.",
        "4.2-8.0s   window fully open (progress=1.0), held -- real "
        "footage (the boy, on the RIGHT of frame) stays visible beside "
        "it the whole time",
        "0.2-1.9s   primary_label \"THE WORLD\" (84px, white -- r197, "
        "was coral; see STANDING TYPOGRAPHY)",
        "1.9-8.0s   primary_label \"THE LAYER\" (84px, white, thin "
        "coral rule beneath -- r197, was solid coral fill)",
        "1.8-8.0s   disclosure \"VISUALIZATION\" (38px), held "
        "continuously from the instant any layer pixel is visible "
        "through the section's end -- r184's own acceptance test "
        "(\"continuous disclosure at every sampled timestamp, "
        "including entry and exit boundaries\")",
    ],
    "borrow": [
        "0.0-12.0s  IMG_6790 @16.0s real footage, continuous",
        "0.0-1.6s   primary_label \"BORROW THE LAYER\" (84px, white, "
        "soft scrim, no box -- r189; every non-hook label lost its "
        "coral fill this round, see STANDING TYPOGRAPHY below)",
        "1.5-3.0s   windowed_reveal(direction=ttb, r197): the AR window "
        "opens top-to-bottom over the LEFT side of frame (the boy stays "
        "visible on the right, walking the same real overlook), "
        "exposing ai/hero/glasses_hero_chatgpt.jpg inside the window "
        "(replaces r185's wipe_reveal)",
        "2.6-7.0s   primary_label \"HARDWARE\" (76px, white, no box)",
        "1.5-7.0s   disclosure \"PRODUCT VISUALIZATION\", held "
        "continuously while the hero plate is on screen",
        "3.2-7.0s   caption \"BORROWED GLASSES — HARDWARE\"",
        "7.0s       hard cut of window content (hero -> "
        "ai/worn/product_worn_falls_park_plate_chatgpt.jpg) -- the "
        "AR window stays fully open (progress=1.0), only the content "
        "inside it swaps, the same \"active aperture, singular\" "
        "logic v36's hwsw beat used for its own hardware/software "
        "swap. This is the exact frame the operator called out by name "
        "(\"there's just that one random picture of an AI model who we "
        "never see again\"): the worn-glasses model now reads as a "
        "framed reference window beside the boy, not a disorienting "
        "full-frame cut to a stranger",
        "7.0-11.4s  primary_label \"SOFTWARE\" (76px, white, no box)",
        "7.0-12.0s  disclosure \"PRODUCT VISUALIZATION\", held "
        "continuously while the worn plate is on screen (including "
        "through the closing sweep)",
        "7.0-11.0s  caption \"PLACE-BASED EXPERIENCE — SOFTWARE\"",
        "11.0-12.0s AR window closes (progress 1.0 -> 0.0) back to "
        "clean real footage, the cut into the next section -- r201: "
        "the ONLY closing sweep in the whole film (every other "
        "windowed_reveal call holds at progress=1.0 until its section "
        "ends). The bracket rectangle now shrinks in lockstep with the "
        "collapsing content (shrink_brackets=True, this call site "
        "only) instead of fading opacity around the still-full-size "
        "window -- see STANDING AR GRAMMAR below.",
    ],
    "recognize": [
        "0.0-12.0s  IMG_6794 @0.0s real footage, full-bleed, continuous "
        "-- r199: the wearer, locked-off wide at the stone overlook "
        "wall, facing across the falls, gesturing/pointing throughout. "
        "Replaces IMG_6805's peopleless 20-33s window (ChatGPT's r198 "
        "review: the wearer was absent for 46 straight seconds here "
        "through loop). This is the FIRST 12.0s of one continuous "
        "41.5s take that also backs examples_hist/ice/audio and loop "
        "(see STANDING WEARER CONTINUITY below) -- one unbroken real "
        "shot spans recognize through loop, not four separate clips.",
        "0.2-1.9s   primary_label \"WHEN THE PLACE RECOGNIZES YOU\" "
        "(72px -- r187, was 62px; r186 caught this against r184's own "
        "72px primary-label minimum, the only miss in that review. "
        "r189: white, soft scrim, no box, same size/position/wording)",
        "1.8-12.0s  zone_trace: four coral corner brackets mark a "
        "bounded zone -- camera-autofocus/AR-bounding-box language, "
        "deliberately NOT v36's node/path rig, which r184 asks this "
        "style to avoid entirely",
        "3.0-12.0s  anchor_pulse: a coral core dot plus a continuously "
        "expanding, fading ring at the zone's anchor point -- \"an "
        "anchored reveal\"",
        "3.2-7.2s   caption \"THE SYSTEM RECOGNIZES WHERE YOU ARE\"",
        "7.2-11.6s  caption \"AND ANCHORS CONTENT TO THIS EXACT PLACE\"",
        "No GPS/computer-vision/beacon/compass/technical-performance "
        "language anywhere in this section, narration included -- "
        "r184's own explicit instruction.",
    ],
    "examples": [
        "r184's own instruction: three unequal, movement-led "
        "transformations branching off recognize, with clean real-"
        "footage resets between them, each in a DISTINCT reveal "
        "direction/rhythm -- not v35's equal EXPERIENCE holds, not "
        "v36's circular apertures/map branches. Rendered as three "
        "independent parts (examples_hist/ice/audio), each its own "
        "process -- the same harness-timeout-avoidance pattern v36's "
        "examples section established (a single ~660-frame build "
        "kept exceeding the background wall-clock limit there).",
        "0.0-1.0s   HISTORICAL part opens on IMG_6794 @12.0s real "
        "footage (reset) -- r199: continues directly from recognize's "
        "own 0.0-12.0s on the SAME unbroken take, the wearer still on "
        "screen, replacing IMG_6805's peopleless reset",
        "1.0-2.2s   windowed_reveal(direction=ltr, r197): the AR window "
        "opens over the LEFT side of frame, exposing IMG_DAK1.MOV (the "
        "same already-disclosed reenactment plate v33-v36 all reuse) "
        "while the SAME real waterfall -- and the wearer, r199 -- stays "
        "visible on the right -- directly answers the operator's own "
        "comparison (\"when we cut to the native family, that's at "
        "least a hard cut... still sucks\"): it is no longer a cut at "
        "all, real and reenacted footage of the same place sit side by "
        "side, with a person actually standing there experiencing it",
        "1.0-8.0s   disclosure \"VISUALIZATION\", held continuously "
        "from the instant any layer pixel is visible",
        "2.2-8.0s   caption \"HISTORICAL RECONSTRUCTION\"",
        "IMG_DAK1.MOV is exactly 8.0s long -- HISTORICAL's duration "
        "matches the real plate exactly rather than requesting more "
        "than exists; ICE AGE absorbs the other 0.5s below so the "
        "section's total (22.0s) is unchanged.",
        "8.0-9.0s   ICE AGE part opens on IMG_6794 @20.0s real footage "
        "(reset) -- r199: same unbroken take, continuing from "
        "HISTORICAL's own 12.0-20.0s window",
        "9.0-10.4s  windowed_reveal(direction=diag, r197): the AR "
        "window opens on a diagonal sweep -- a distinct direction from "
        "historical's left-to-right -- exposing the Ice Age plate "
        "inside the window while the same real falls stay visible "
        "beside it",
        "9.0-17.5s  disclosure \"VISUALIZATION\", held continuously",
        "10.4-17.5s caption \"ICE AGE VISUALIZATION\"",
        "17.5-18.5s AUDIO part opens on a still grabbed at IMG_6794 "
        "@29.5s (reset) -- r199: the exact instant ICE AGE's own read "
        "ends, so the wearer's take carries straight through with no "
        "time jump; the same still-frame technique v35/v36 used for "
        "their own spatial-audio segment",
        "18.5-22.0s two overlapping anchor_pulse rings, now at "
        "(0.34W, 0.34H) -- r199: shifted off center (was 0.5W, 0.42H) "
        "so the anchor sits over open falls/sky instead of grazing the "
        "wearer's head/shoulder in this composition (a simple "
        "synchronized-audio visual, not a wipe) -- no disclosure tag, "
        "since this is a real-footage still, not fabricated imagery",
        "18.7-22.0s caption \"SPATIAL AUDIO, SYNCHRONIZED\"",
        "17.5-22.0s r208: gentle continuous push-in (1.00x -> 1.07x "
        "across the part's own 4.5s), the same device r193 established "
        "for loop -- this still was previously held perfectly static "
        "for its whole duration, the one section with LESS motion than "
        "loop had before r193 (loop was at least real footage; this "
        "was one frame from the very start)",
        "Durations 8.0 / 9.5 / 4.5s (including each part's own reset) "
        "are still distinct -- the unequal rhythm r176/r178/r184 all "
        "require is unchanged in spirit, applied with three genuinely "
        "different reveal mechanisms this time.",
    ],
    "loop": [
        "0.0-12.0s  IMG_6794 @29.5s real footage, full-bleed, "
        "continuous -- r199: the LAST 12.0s of the same unbroken take "
        "that opens recognize and backs all three examples parts, so "
        "the wearer is on screen for the words too, not just a returned "
        "empty view. No wipe, no text-heavy diagram, \"real footage "
        "and two or three large words at a time\" per r184's own "
        "explicit instruction. r193's gentle continuous push-in "
        "(1.00x -> 1.07x across the section, center-crop on the "
        "already-loaded frame) is unchanged -- still the only "
        "full-bleed section with no camera motion of its own.",
        "0.0-3.0s   \"BORROW\" / \"the hardware\"",
        "3.0-6.0s   \"EXPERIENCE\" / \"the story\"",
        "6.0-9.0s   \"RETURN\" / \"the hardware\"",
        "9.0-12.0s  \"UPDATE\" / \"the software\"",
        "One word pair on screen at a time -- never four nodes "
        "simultaneously the way v36's own loop section did. r197: the "
        "sub-caption (\"the hardware\"/\"the story\"/etc.) is now white, "
        "was coral -- see STANDING TYPOGRAPHY.",
    ],
    "close": [
        "0.0-8.0s   IMG_6790 @22.0s real footage, full-bleed, "
        "continuous -- a different sub-window from hook's own 8.0s "
        "and borrow's own 16.0s in-points on the same 32.0s-long clip",
        "0.0-4.5s   caption \"OPEN RANGE INTERACTIVE ADDS A STORY "
        "LAYER TO REAL PLACES\" -- the \"one concise definition of "
        "ORI\" r184's own beat 6 asks for",
        "4.5-8.0s   end_card \"OPEN RANGE INTERACTIVE\" / \"PLACE-"
        "BASED STORIES, LAYERED ONTO REAL PLACES\", held through the "
        "literal last rendered frame (true no-fade path, the same fix "
        "v35's r175 round landed on and v36 carried forward from the "
        "start -- fade_k's no_out=True flag, not a fresh discovery)",
    ],
}


def main():
    L = []
    L.append('ORI v37 -- "THE WORLD / THE LAYER" (hook gaze alignment, r203)')
    L.append("Fifth and final execution in the operator-ordered five-style "
             "slate (r145__operator__five_style_variants.md); v33/r167, "
             "v34/r173 are frozen, v35/r177 is visually locked pending "
             "only an operator audio spot-check, v36/r183 is frozen per "
             "r184's own review. r186/r188 passed and froze this style's "
             "picture on ChatGPT's own rubric. The operator then looked at "
             "the delivered film directly and called it out: every label, "
             "caption and disclosure sat inside a hard-edged solid-fill "
             "rectangle -- a chyron/lower-third convention, not how a "
             "premium product film sets type, and coral filled every "
             "single label rather than reading as a rare accent. r189 "
             "rewrote graphics_layer.py to replace every box with a soft "
             "feathered scrim and blurred-halo text, and reserved coral "
             "for the hook's own title toggle only. r190 approved that "
             "direction but found it overcorrected: plain white type with "
             "only a soft halo washed out over pale sky, snow, bright "
             "concrete and bright hair. r191 strengthens the local scrims, "
             "front-loads the bottom-edge gradient's rise, and adds a "
             "crisp keyline stroke under the halo on every disclosure and "
             "caption, plus the end card (now white on both lines, coral "
             "reserved for the separator rule) -- still boxless, now "
             "legible over any background. r192 reviewed r191 and froze "
             "v37's picture on ChatGPT's own rubric. r193 is a further "
             "self-directed craft pass, not a response to a flagged "
             "review finding: the operator asked to keep improving the "
             "look, and this session's own fresh re-watch found the loop "
             "section (54.0-66.0s) was the one full-bleed section in the "
             "film with zero camera motion for its whole 12s -- every "
             "other full-bleed section's footage carries some inherent "
             "camera movement, this one reads close to locked-off. "
             "build_loop() now applies a gentle continuous push-in "
             "(1.00x -> 1.07x across the section) directly on the real "
             "footage -- the same device this film's own wipes already "
             "use on its AI plates. No footage swap, no wording, no "
             "disclosure, no timing, and the 74.000s runtime are "
             "unchanged; only the loop section's camera motion. r194 "
             "reviewed r193 and updated the v37 picture freeze to it. "
             "The operator then said 'the whole vibe' was still off. "
             "Every prior report for this style claimed 'narration only, "
             "no score -- the same judgment call every prior style in "
             "this slate has made' -- that was never actually checked: "
             "v33 (one/) and v34 (field/) both ship a synthesized, "
             "license-clean score, wired the same way this build now "
             "wires score_layer.py. r195 adds that score (bright C-G-Am-F "
             "progression, quiet under the hook's own wipe reveal, a "
             "swell under the richest section (examples), easing back "
             "for the loop's four words, released before the end card) "
             "mixed under narration exactly like field/assemble_field.py "
             "mixes its own. Picture is pixel-identical to r193; only "
             "the audio changed.")
    L.append(f"Running time {TOTAL:.3f}s   {W}x{H} @ {FPS} fps, full 16:9, no scope crop")
    L.append("")
    L.append("SECTION LIST -- generated from spec_layer.py, not retyped")
    L.append("")
    for s, st, d, desc in SECTIONS:
        L.append(f"  {st:5.1f}-{st+d:5.1f}  {s:<10} {desc}")
    L.append("")
    L.append("SHOT STRUCTURE, DISCLOSURE INTERVALS -- read from render_layer.py's own code")
    L.append("")
    for s, st, d, desc in SECTIONS:
        for line in STRUCTURE.get(s, []):
            L.append(f"  {line}")
        L.append("")
    L.append("NARRATION, VERBATIM -- read from vo_layer.py, not retyped "
              "(synthesized offline, piper en_US-lessac-high; no licensed "
              "or cloned voice; a COMPLETELY FRESH script -- sentence "
              "architecture and opening do not reuse v35 or v36, per "
              "r184's explicit instruction)")
    L.append("")
    for sec, off, text in VO_LINES:
        sst = next(s[1] for s in SECTIONS if s[0] == sec)
        L.append(f"  {sst + off:5.1f}s  \"{text}\"")
    L.append("")
    L.append("  No date, no measurement, no attribution, no traction, no "
              "partnership, no deployment claim, no CTA, no GPS/computer-"
              "vision/beacon/compass/precision/latency implementation "
              "detail -- all explicitly ruled out by r184, same as r178 "
              "before it.")
    L.append("")
    L.append("STANDING DISCLOSURE")
    L.append("  \"VISUALIZATION\" over the Ice Age plate (hook, examples) "
             "and the historical reenactment plate (examples); "
             "\"PRODUCT VISUALIZATION\" over the hero-glasses and worn "
             "plates (borrow). All held CONTINUOUSLY for their complete "
             "on-screen interval (disclosure() defaults to fixed k=1.0, "
             "no fade envelope at all -- same discipline v35's r175 "
             "established, carried forward by every style since), at "
             "38px -- r184's own minimum, given from the first pass "
             "rather than needing a follow-up legibility round the way "
             "v36 did. The spatial-audio example carries no tag because "
             "it is a real-footage still, not fabricated imagery. No "
             "system-diagram tag or node/path language anywhere in this "
             "style, per r184's own explicit instruction to avoid v36's "
             "\"node-map language\" -- the real/visualized boundary is "
             "communicated by the wipe grammar itself (world vs. layer) "
             "plus these disclosure tags. r189: rendered as tracked "
             "small-caps with a soft halo instead of a dark box -- reads "
             "as an integrated credit line now, same words, same "
             "interval, same 38px minimum, same corner position. r191 "
             "(r190's finding): the tracked white letters nearly "
             "disappeared over pale sky/snow with only a halo behind "
             "them -- added a feathered local scrim and a crisp keyline "
             "stroke; still boxless, same words/interval/size/position, "
             "now legible over any background.")
    L.append("")
    L.append("STANDING TYPOGRAPHY (r189, legibility-corrected r191)")
    L.append("  Every text element in r185-r188's delivered cut sat inside "
             "a hard-edged solid-fill rectangle -- primary labels in a "
             "coral box, captions in a black bar, the loop words in a "
             "black chip, the end card in a black card. That reads as a "
             "chyron/lower-third convention (news captions, corporate "
             "training video), not how a premium product film sets type, "
             "and it was the operator's own direct catch, not a ChatGPT "
             "review finding -- r186/r188 graded this film against r184's "
             "numeric minimums and never flagged the box treatment "
             "itself. graphics_layer.py now replaces every box with a "
             "soft feathered scrim (a blurred alpha patch, not a hard "
             "edge) and blurred-halo text (a soft dark duplicate of the "
             "glyphs behind the crisp glyphs -- the same legibility a box "
             "gave, without the box). Coral is now reserved for the "
             "hook's own \"THE WORLD\"/\"THE LAYER\" title toggle; every "
             "other beat's primary label (BORROW THE LAYER, HARDWARE, "
             "SOFTWARE, WHEN THE PLACE RECOGNIZES YOU) is clean white, so "
             "the accent reads as a rare, designed moment instead of a "
             "wash of red on every frame. No footage, wipe, disclosure "
             "wording, caption wording, narration, timing, section "
             "boundary, or the 74.000s runtime changed -- only how the "
             "type renders. Zone-trace brackets and the anchor pulse are "
             "unchanged (they were never boxed text).")
    L.append("  r191 (r190's own finding, timestamped): plain white type "
             "with only a soft halo washed out at 5.6-7.0s and 42.8-49.0s "
             "(the VISUALIZATION disclosure over pale sky/snow), "
             "16.8-18.2s (PRODUCT VISUALIZATION over bright hair/sky), "
             "22.8-30.8s and 33.6-39.2s and 66.0-69.2s (bottom captions "
             "over bright grass/river-rock/concrete), and 70.6-73.9s (the "
             "end card's coral second line over the bright overlook). "
             "disclosure() and caption() now add a feathered local scrim "
             "(disclosure) or a front-loaded bottom-edge gradient "
             "(caption) plus a crisp 2px dark keyline stroke under the "
             "existing soft halo -- still no hard rectangle, contrast "
             "held over any background. end_card()'s second line is now "
             "white instead of coral (coral reserved for the separator "
             "rule alone) with a stronger local scrim. Primary labels, "
             "loop words, and the zone-trace/anchor-pulse graphics were "
             "not touched -- r190 asked to preserve them, and this "
             "session's own re-check of the r189 delivery found them "
             "already legible. Font sizes, wording, timing, positions, "
             "and the 74.000s runtime are unchanged.")
    L.append("  r197 (operator direct note: \"that orange text color... "
             "it's ugly, it sucks\"): coral is now reserved ENTIRELY for "
             "geometric elements -- thin rule lines, corner brackets, "
             "the AR-window wipe seam, the anchor-pulse dot/ring -- "
             "never a text/glyph fill, on any call, anywhere in the "
             "style. primary_label() renders every label in white "
             "regardless of its accent_bg argument; accent_bg=True (the "
             "hook's own \"THE WORLD\"/\"THE LAYER\" toggle) now adds "
             "only a thin coral rule beneath the white text, not a "
             "colored glyph fill. loop_word()'s sub-caption "
             "(\"the hardware\"/\"the story\"/etc.) is white, was coral. "
             "end_card() was already fixed to white-on-both-lines in "
             "r191 and is untouched this round. Re-rendered: hook, "
             "borrow (both had accent_bg defaulting True on \"THE "
             "WORLD\"/\"THE LAYER\"/\"HARDWARE\"/\"SOFTWARE\"), "
             "recognize and loop (their own label calls already passed "
             "accent_bg=False, so their text was already white before "
             "this round -- re-rendered anyway to confirm, byte-size-"
             "identical output on recognize confirms no regression). "
             "examples_audio and close use no primary_label/loop_word "
             "call and needed no re-render.")
    L.append("")
    L.append("STANDING AR GRAMMAR (new this round, r197)")
    L.append("  Operator direct critique, verbatim: \"we cut to an AI "
             "image, it's out of place... you fade to a place that's "
             "not... anything to do with the guy... there's just that "
             "one random picture of an AI model who we never see again, "
             "so much AI slop... it doesn't give the feel, it's supposed "
             "to be a very streamlined feel -- you walk around with "
             "glasses and you see stuff. All these hard cuts and places "
             "that people aren't walking around, they have no life, no "
             "pathos, no ethos.\" Root cause: every AI/product reveal in "
             "r185-r195 used wipe_reveal(), a FULL-FRAME crossfade that "
             "swapped the entire picture to an unrelated photo -- a "
             "different place, a different person, sometimes a "
             "different person's face entirely (the worn-glasses model "
             "at 7.0-11.4s). That is structurally backwards for a "
             "\"you walk around with AR glasses\" film: the real place "
             "should never disappear. windowed_reveal() (graphics_"
             "layer.py) replaces it everywhere (hook, borrow, "
             "examples_hist, examples_ice -- 4 call sites, wipe_reveal "
             "itself deleted, zero callers left): the real world stays "
             "full-bleed at EVERY value of progress; the AI/product "
             "content only ever appears inside a floating window, "
             "bracket-framed with the EXACT SAME corner-bracket drawing "
             "and geometry recognize's own zone_trace already uses "
             "(reused deliberately -- the whole film now reads as one "
             "consistent AR system, not a different effect per section), "
             "directional reveal sweep confined to the window's own "
             "bounds, coral seam at the sweep's leading edge while "
             "mid-open. The wearer (hook/borrow, and r199: recognize/"
             "examples/loop too) and the falls themselves stay visible "
             "beside the window at every timestamp checked -- no "
             "collision with the disclosure tag (top-right) or the "
             "bottom captions in any re-rendered section, confirmed on "
             "real frame grabs, not just the synthetic smoke test "
             "windowed_reveal() was unit-tested against before wiring "
             "it in. Window geometry (WIN_CX/CY/W/H in graphics_"
             "layer.py) is a direct constant copy of recognize's "
             "ZONE_CX/CY/W/H in render_layer.py -- one AR window "
             "position/size for the whole film.")
    L.append("  r198 (ChatGPT's review of r197): PASSED the white-type "
             "correction and the core windowed-reveal approach, but "
             "REJECTED freezing the picture on two grounds: (1) the "
             "wearer still disappeared for 46 straight seconds (00:20-"
             "01:06) because recognize/examples/loop drew from IMG_"
             "6805, a different, peopleless clip -- \"places where "
             "nobody is walking around have no life, no pathos, no "
             "ethos,\" the operator's own point, still true after r197's "
             "fix; (2) the window's drop shadow and static-strength "
             "brackets still read as \"a floating picture-card,\" and "
             "the closing sweep at ~00:19 left \"only a thin strip of "
             "content inside the still fully drawn aperture\" -- \"a "
             "collapsing crop, not a clean AR dismissal.\" See STANDING "
             "WEARER CONTINUITY below for (1); for (2), windowed_"
             "reveal()'s scrim is now tighter and lower-alpha (padding "
             "ww/2+6 not +20, alpha up to 60 not 130, centered, no "
             "offset -- a legibility scrim, not a card shadow) and "
             "zone_trace's k now tracks p*1.15 instead of p*2.5, so the "
             "brackets shrink in step with the revealed content on "
             "BOTH open and close instead of snapping to full strength "
             "by p=0.4 and holding there through most of a close.")
    L.append("  r200 (ChatGPT's re-check of r199, verbatim): \"the four "
             "large corner brackets still occupy the full original "
             "window bounds. The bottom two corners are plainly visible "
             "far below the remaining content... two animations that "
             "are not spatially coupled.\" r198's opacity fade was not "
             "steep enough on its own. r201: windowed_reveal() gained "
             "`shrink_brackets` (default False, off everywhere except "
             "one call site). When True, the bracket rectangle's "
             "relevant axis is clamped to `boundary` -- the exact same "
             "value the coral seam line is drawn at -- so the bracket "
             "edge and the seam are always the same position; the "
             "brackets can never enclose empty space. render_layer.py "
             "passes shrink_brackets=(t>=11.0) only in build_borrow(), "
             "i.e. only during borrow's own closing sweep -- the ONE "
             "call site in the whole film that actually closes back to "
             "0 (every other windowed_reveal call holds at progress=1.0 "
             "until its section ends, so shrink_brackets would be a "
             "no-op there anyway). No other shot's bracket behavior "
             "changed. Verified on real rendered frames at ChatGPT's "
             "own six requested timestamps, 00:19.0 through 00:20.0 at "
             "0.2s steps: the bracket visibly shrinks in lockstep with "
             "the collapsing content at every one, fully gone by "
             "~00:19.8 alongside the content.")
    L.append("  r201 (operator direct note on the delivered r199 cut: "
             "\"this don't look any better\" -- \"the floating window "
             "itself still looks cheap/flat\"): windowed_reveal() now "
             "feathers the window's own outer edges -- the two sides "
             "perpendicular to the sweep direction (top/bottom for "
             "ltr, left/right for ttb; all four for diag, which never "
             "closes in this build) -- with a ~20px falloff, instead of "
             "a crisp rectangular cut on those sides (the sweep's own "
             "leading edge already had a soft `edge` feather; the "
             "window's STATIC sides did not). A soft glowing rim (a "
             "blurred, cool-white 5px outline just outside the window "
             "bounds, alpha scaling in with progress) now sits at the "
             "boundary too. Both are standard, cheap compositing cues "
             "for \"a projected light layer,\" not a redesign of the "
             "window's size, position, or the reveal mechanism itself. "
             "Confirmed via direct frame comparison against the exact "
             "beats the operator screenshotted (hook's THE LAYER, "
             "borrow's SOFTWARE, examples' HISTORICAL RECONSTRUCTION): "
             "edges read softer, less like a pasted rectangle. Not "
             "claimed to fully resolve \"cheap/flat\" on its own -- see "
             "R201 -- THE OPERATOR'S DIRECT RESPONSE above for the "
             "gaze-mismatch finding, which is very likely the larger "
             "remaining factor and is NOT fixable by this or any other "
             "compositing change against the currently available "
             "footage.")
    L.append("  r203 (ChatGPT's r202 pushback on r201's 2-clip gaze "
             "check, and the full 33-clip audit it prompted): hook's "
             "windowed_reveal() call now passes win_cx=1000/1920, "
             "win_cy=470/1080 -- shifted from the shared default (used "
             "everywhere else in the film) to sit where the wearer's "
             "own pointing gesture (see hook's own STRUCTURE entry "
             "above, local t~3.0-6.5s) actually lands. This is a "
             "per-shot override, not a change to the shared WIN_CX/"
             "CY_FRAC constant -- recognize's zone_trace and every "
             "other windowed_reveal call keep the original position. "
             "One shot, found by full audit, actually has a gesture to "
             "align to; the rest do not.")
    L.append("")
    L.append("STANDING WEARER CONTINUITY (new this round, r199)")
    L.append("  ChatGPT's r198 review, verbatim: \"the wearer disappears "
             "for the entire 00:20-01:06 middle: 46 seconds of the "
             "74-second film sit on the same peopleless base view... "
             "A viewer therefore watches a person demonstrate the "
             "premise, loses him for nearly two-thirds of the runtime, "
             "and sees him return only for the close.\" This is the same "
             "root complaint the operator raised at r196 (\"no life, no "
             "pathos, no ethos\") persisting in a new form after r197's "
             "picture-compositing fix, because that fix never touched "
             "WHICH footage recognize/examples/loop drew from -- only "
             "how the AI/product content was composited over it. "
             "recognize, examples_hist, examples_ice, examples_audio "
             "and loop now all draw from ONE continuous, unbroken take "
             "of the wearer instead: IMG_6794 (a 54.4s locked-off wide "
             "shot at the stone overlook wall, the wearer facing away/"
             "across the falls, gesturing and pointing throughout -- "
             "already identified as \"the wearer\" by one/spec_one.py's "
             "own prior scouting of this same raw footage library). "
             "0.0-12.0s backs recognize, 12.0-20.0s examples_hist, "
             "20.0-29.5s examples_ice, 29.5s (a single frame) examples_"
             "audio's still, 29.5-41.5s loop -- one unbroken 41.5s span "
             "out of the clip's 54.4s (12.9s to spare), so the section "
             "boundaries land on the SAME real take rather than cutting "
             "to a different clip: the wearer is present, in the same "
             "shot, continuously, for the entire recognize->examples->"
             "loop stretch. AR window placement was verified against "
             "this specific take at 4s intervals across its full 0-44s "
             "range (frame grabs with the window's exact bounds drawn "
             "on top): the wearer stays right-of-frame throughout, "
             "never entering the window's bounds (the left third of "
             "frame, over open falls/sky) -- confirmed, not assumed. "
             "examples_audio's anchor_pulse position also moved (0.34W, "
             "0.34H, was 0.5W/0.42H) after the original center position "
             "was found grazing the wearer's head/shoulder in this "
             "specific composition. Not touched: hook/borrow/close "
             "still use IMG_6790, a different clip (also featuring the "
             "wearer) -- the section cut between borrow and recognize "
             "is a genuine shot change like every other section "
             "boundary in the film, not a continuity break introduced "
             "by this round.")
    L.append("")
    L.append("R200 -- CHATGPT'S REVIEW OF R199, AND WHAT R201 FIXES")
    L.append("  ChatGPT's r200 review passed r199's wearer-continuity fix "
             "outright (\"the same wearer remains visible throughout "
             "recognize, historical, Ice Age, spatial audio, and the "
             "four-word loop... directly answers the operator's 'no "
             "life, no pathos, no ethos' criticism\") and passed the "
             "overall window treatment, but held picture freeze on one "
             "narrow remaining point, verbatim: \"At 00:19.4, the "
             "software plate has collapsed to a shallow strip at the "
             "top of the aperture, but the four large corner brackets "
             "still occupy the full original window bounds. The bottom "
             "two corners are plainly visible far below the remaining "
             "content... The current frame reads as two animations "
             "that are not spatially coupled.\" r198's opacity-only fix "
             "(k tracking p) was not enough: at p=0.648 the brackets "
             "were still ~75% opaque even though the revealed content "
             "had shrunk well below half the window's height. r201 "
             "fixes the actual GEOMETRY, not just the opacity -- see "
             "STANDING AR GRAMMAR below -- verified on real rendered "
             "frames at ChatGPT's own six requested timestamps (00:19.0 "
             "through 00:20.0 at 0.2s steps).")
    L.append("")
    L.append("R201 -- THE OPERATOR'S DIRECT RESPONSE TO THE DELIVERED r199 CUT")
    L.append("  Before r201 could ship, the operator watched the "
             "delivered r199 master directly (3 screenshots: the "
             "historical-reconstruction beat, the HARDWARE beat, and "
             "the hook's own THE LAYER beat) and said plainly: \"this "
             "don't look any better.\" Asked to narrow it down, two "
             "things were confirmed: (1) the wearer's gaze never meets "
             "the window -- in every screenshot he is looking down, "
             "forward, or adjusting his hair, never toward the floating "
             "content beside him, so the window reads as juxtaposed "
             "rather than seen; (2) the window itself still reads as a "
             "flat, pasted photo rather than an integrated AR layer, "
             "brackets and reduced shadow notwithstanding. Both were "
             "checked directly against the raw footage rather than "
             "assumed:")
    L.append("  (1) GAZE -- verified, NOT fixable with existing footage. "
             "Sampled IMG_6794 (recognize/examples/loop's own take) at "
             "2s intervals across its full 0-52s range and IMG_6790 "
             "(hook/borrow) at 2s intervals across its own used stretch: "
             "in IMG_6794 the wearer faces away from camera toward the "
             "falls for the ENTIRE take, arm gestures (pointing, "
             "touching his hair) are the only variation -- he never "
             "turns his head back toward camera-left, where the window "
             "sits. In IMG_6790 he is in profile, facing left toward "
             "real signage in front of him, not toward the window's "
             "specific position. Both clips are candid, real footage "
             "shot for their own sake, not staged reaction shots for a "
             "VFX composite -- there is no frame in either clip where "
             "he is deliberately looking at a point that would later "
             "hold an AR window. Fixing this for real needs NEW footage "
             "(the operator or a future capture session filming him "
             "actually looking toward a marked spot), not a compositing "
             "change -- flagged here rather than faked, per rule zero.")
    L.append("  (2) WINDOW TREATMENT -- fixed, within what compositing "
             "alone can do. windowed_reveal() now feathers the window's "
             "own outer edges (the two sides perpendicular to the sweep "
             "direction -- the sweep's own leading edge already faded) "
             "and adds a soft glowing rim at the boundary once content "
             "is showing: a light blue-white blurred outline, scaling "
             "in with progress. These are the two standard, cheap "
             "compositing cues for \"this is a projected light, not a "
             "photo card.\" Honest limit: this is a real, verifiable "
             "improvement in the edge treatment, not a claim that the "
             "window now looks fully premium -- the deeper gaze problem "
             "in (1) is very likely still the dominant thing a viewer "
             "notices, and no compositing-only change resolves it.")
    L.append("")
    L.append("R202 -- CHATGPT'S REVIEW OF R201, AND WHY R203 IS A FULL AUDIT")
    L.append("  ChatGPT's r202 review passed the r201 aperture-close fix "
             "outright (\"the six dense boundary samples show the closing "
             "image and its coral brackets shrinking together... the "
             "aperture now closes cleanly\") but pushed back, correctly, "
             "on r201's gaze finding, verbatim: \"the operator brief says "
             "the production holds 60+ clips/photos, so an 'unfixable "
             "with existing footage' conclusion requires a complete "
             "source audit.\" r201 had checked only IMG_6794 and "
             "IMG_6790 -- 2 of 33 real candid clips in the raw library. "
             "r203 is that complete audit: every clip sampled at 3 "
             "points minimum, full-resolution follow-up wherever the "
             "wearer appeared in any orientation besides back-to-camera. "
             "See r203__claude__v37_gaze_alignment_audit.md for the full "
             "33-row table.")
    L.append("R203 -- WHAT THE FULL AUDIT FOUND")
    L.append("  One genuine candidate, previously missed: IMG_6790 raw "
             "t~3.5-7.0s, a stretch that sits BEFORE hook's own in-point "
             "(which started at t=8.0, by which point he has already "
             "turned his back and is walking away -- exactly the "
             "orientation the operator's own r201 screenshot showed). In "
             "this earlier stretch he turns toward camera and extends "
             "his arm in a clear pointing gesture at real signage. hook's "
             "own in-point moved to t=0.5 (8.0s duration, same as "
             "before, just 7.5s earlier in the same clip -- a 0.4s "
             "finger-over-lens artifact at the very start of the raw "
             "file is why the in-point isn't t=0.0). The AR window is "
             "repositioned for this one shot (win_cx=1000/1920, "
             "win_cy=470/1080 -- his pointing hand lands right at the "
             "window's edge) -- see STANDING AR GRAMMAR. Every other "
             "section (borrow, recognize, examples, loop) has no "
             "comparable moment anywhere in the 33-clip library -- "
             "second people present, back-to-camera throughout, framing "
             "incompatible with a window, too short, or unrelated content "
             "entirely (screen recordings). Those remain a genuine "
             "capture gap; see r203__claude__v37_new_capture_brief.md "
             "for exactly what new footage would resolve it.")
    L.append("")
    L.append("R204-R206 -- CHATGPT CONFIRMS R203, REDUCES TO AN OPERATOR "
             "CHOICE, THEN CONFIRMS THE WAIT STATE")
    L.append("  r204 passed the hook fix and the audit outright, but "
             "caught a real contradiction in r203's own capture brief "
             "(its own section list totaled six clips while its "
             "technical summary said four minimum/five total). r205 "
             "corrected this with no render -- ChatGPT explicitly said "
             "not to touch the source library or compositing again -- "
             "superseding the r203 brief with the minimum real ask: two "
             "staged setups (borrow, examples), three takes each. r206 "
             "confirmed the correction and reduced the whole thread to "
             "the operator's exact binary choice (provide the footage, "
             "or accept the mismatch and freeze at r203), instructing "
             "Claude to do nothing further until one of those happens. "
             "Both remain open as of this round; r208 below is "
             "independent of that decision and doesn't require it "
             "resolved first.")
    L.append("")
    L.append("R208 -- SELF-DIRECTED CRAFT PASS: THE STATIC SPATIAL-AUDIO "
             "STILL")
    L.append("  Not a response to a flagged review finding -- the "
             "operator asked to keep improving the film while r206's "
             "capture decision and r207's bespoke-AI-image request "
             "(sent to ChatGPT, seeking shot-matched Ice Age/hardware/ "
             "software plates in place of the current mismatched/reused "
             "generic ones -- see r207__claude__bespoke_ai_image_request.md) "
             "both sit outside what Claude can resolve alone. A fresh "
             "frame-by-frame re-watch of the whole film found one real, "
             "previously uncaught defect squarely inside what Claude "
             "CAN fix without new footage or new imagery: examples_audio "
             "(17.5-22.0s, the spatial-audio beat) was a single frame, "
             "grabbed once and held perfectly static for its entire "
             "4.5s -- the same 'zero camera motion' defect r193 found "
             "and fixed for loop, just never caught here because this "
             "section was never even real video to begin with, only a "
             "still. build_examples_audio() now applies the identical "
             "gentle 1.00x->1.07x continuous push-in r193 established "
             "for loop, scaled to this part's own duration. This is the "
             "only change this round -- no footage swap, no wording, no "
             "disclosure, no timing, no score/mix change, and the "
             "74.000s runtime is unchanged; the full-film contact sheet "
             "was re-reviewed end to end and shows no regression "
             "elsewhere.")
    L.append("")
    L.append("SOUND")
    L.append("  r195: narration plus a synthesized score (score_layer.py) "
             "-- no sample, nothing licensed, regenerable from source at "
             "any length. Bright C-G-Am-F progression, 96 BPM, mixed under "
             "narration at weight 0.55 vs. the voice's 1.0 (the same "
             "balance field/assemble_field.py's own mix uses). Quiet "
             "under the hook's clean-footage open, lifts through the "
             "wipe reveal (1.8-4.2s), sustains through borrow/recognize, "
             "swells under examples (32.0-54.0s, the richest passage), "
             "eases back for the loop's four words so they aren't "
             "fighting a swell, and releases before the end card. r185- "
             "r193 all claimed this was 'the same judgment call every "
             "prior style in this slate has made' -- that was never "
             "checked against the other four builds: v33 (one/) and v34 "
             "(field/) both ship a score already, wired the same way. "
             "Measured -16.55 LUFS integrated / -1.94 dBTP true peak "
             "(no clipping: volumedetect max_volume -1.5 dB, right at "
             "the limiter's own ceiling). This session has no audio "
             "playback capability, so the mix's musical/emotional fit "
             "is not something it can verify by ear -- only that the "
             "signal is present, level-matched, and clean. ChatGPT's "
             "r196 async review (reading r195's Drive files, not this "
             "chat) recommended freezing picture pending an operator "
             "audio listening verdict on r195 -- written before the "
             "operator's own direct critique below arrived; r197 "
             "superseded that hold on the operator's explicit, more "
             "recent instruction to rework the picture. r199, r200 and "
             "r201 are all further picture-only rounds since -- r195's "
             "score and its open six-part audio spot-check are still "
             "carried forward untouched, unchanged since r195.")
    L.append("")
    L.append("R197 -- THE OPERATOR'S DIRECT 5-SCREENSHOT CRITIQUE")
    L.append("  The operator watched the delivered r195 film and gave "
             "detailed, specific feedback with 5 screenshots, naming two "
             "problems: (1) \"that orange text color... nothing "
             "professional about it... it just got slapped on there\"; "
             "(2) every AI/product cutaway was a full-frame swap to a "
             "totally unrelated photo/place/person -- \"we cut to an AI "
             "image, it's out of place,\" \"there's just that one random "
             "picture of an AI model who we never see again... so much "
             "AI slop,\" \"these fades... you fade to a place that's not "
             "not where the guy standing, not anything to do with the "
             "guy.\" The structural point: \"it doesn't give the feel. "
             "It's supposed to be a very streamlined feel -- you walk "
             "around with glasses like the guy's doing in my videos and "
             "you see stuff. All these hard cuts and places that people "
             "aren't walking around, they have no life, no pathos, no "
             "ethos.\" Both are fixed in this round -- see STANDING "
             "TYPOGRAPHY and STANDING AR GRAMMAR below -- using only "
             "already-approved assets recomposited differently; no new "
             "image/video was generated (standing rule: Claude never "
             "generates imagery, ChatGPT only).")
    print("\n".join(L))


if __name__ == "__main__":
    main()
